services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    volumes:
      - myvolume:/data/db
    networks:
      - mongodb-net

  mongoexpress:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secretpassword
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    networks:
      - mongoexpnetwork

  nodeapp:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongoexpnetwork


volumes:
  myvolume:
networks:
  app-network01:
    name: app-network01
  mongodb-net:
    name: mongodb-net
  mongoexpnetwork:
    name: mongoexpnetwork


